apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dev-web
  namespace: dev-monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - dev
  selector:
    matchLabels:
      app: web
  endpoints:
    - port: http
      path: /metrics
      interval: 15s