grafana:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - monitoring.localhost
    path: /
    pathType: Prefix

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      folderAnnotation: grafana_folder
      provider:
        foldersFromFilesStructure: true

    # OJO: esto es lo que te arregla el datasource y tu UID "prometheus"
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
      isDefaultDatasource: true
      name: Prometheus
      uid: prometheus
      url: http://monitoring-kube-prometheus-prometheus:9090

# En k3s/k3d, para evitar ruido/targets que no existen (muy típico), desactivamos scrapes de control-plane
kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false

# Y desactivamos reglas por defecto que dependen de esos componentes (si no, te saldrán alertas “basura”)
defaultRules:
  create: true
  rules:
    etcd: false
    kubeControllerManager: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false

# Alertas por entorno
additionalPrometheusRulesMap:
  dev-app-rules:
    groups:
      - name: dev.web.availability
        rules:
          - alert: DevWebReplicasNotReady
            expr: kube_deployment_status_replicas_available{namespace="dev", deployment="web"} < 2
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "DEV: web con menos de 2 réplicas disponibles"
              description: "deployment dev/web tiene menos de 2 réplicas disponibles durante más de 2 minutos."

  pro-app-rules:
    groups:
      - name: pro.web.availability
        rules:
          - alert: ProWebReplicasNotReady
            expr: kube_deployment_status_replicas_available{namespace="pro", deployment="web"} < 4
            for: 2m
            labels:
              severity: critical
            annotations:
              summary: "PRO: web con menos de 4 réplicas disponibles"
              description: "deployment pro/web tiene menos de 4 réplicas disponibles durante más de 2 minutos."
